apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polbro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Christian-Tiovanto/k8s-polling.git'
    targetRevision: HEAD
    path: charts/polbro-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true